name: Auto Check Solution

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
    create-pull-requst:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: main
        - name: Setup Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.x'
            architecture: 'x64'
        - name: Setup Python Package
          run: |
            python -m pip install --upgrade pip
            pip install bs4 requests
        - name: tagging (1. Run script)
          run: |
            python scripts/check_pull_request.py --check_solution --pr_number ${{ github.event.number }}
            echo "SOLUTION_LANG=`head -1 result`" >> $GITHUB_ENV
        - name: add Label
          if: contains(github.event.pull_request.labels.*.name, 'Solution') == false
          uses: actions/github-script@v4
          with:
            script: |
              const { SOLUTION_LANG } = process.env
              if (SOLUTION_LANG == "python") {
                github.issues.addLabels({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: ["Python", "Solution"]
                });
              }
              else if(SOLUTION_LANG == "cpp") {
                github.issues.addLabels({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: ["C++", "Solution"]
                });
              }
              else if(SOLUTION_LANG == "java") {
                github.issues.addLabels({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: ["Java", "Solution"]
                });
              }
        - name: Check Solution
          run: |
            python scripts/check_pull_request.py --pr_number ${{ github.event.number }}
